# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web_weak_scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 548)
        Dialog.setStyleSheet("background-color: rgb(12, 63, 91);")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 100, 461, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 150, 251, 28))
        self.pushButton.setStyleSheet("background-color: rgb(57, 255, 239);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 150, 251, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(57, 255, 239);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(40, 210, 461, 271))
        self.listView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 500, 93, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(62, 255, 233);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 70, 251, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 251, 51))
        font = QtGui.QFont()
        font.setFamily("경기천년제목 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "직접 입력 모드"))
        self.pushButton_2.setText(_translate("Dialog", "List 입력 모드"))
        self.pushButton_3.setText(_translate("Dialog", "확인"))
        self.label.setText(_translate("Dialog", "도메인 혹은 IP 주소를 입력하세요."))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; font-style:italic; color:#efff57; vertical-align:super;\">Web </span><span style=\" font-size:18pt; font-weight:600; font-style:italic; color:#efff57;\">Weak </span><span style=\" font-size:26pt; font-weight:600; font-style:italic; color:#efff57; vertical-align:sub;\">Scan</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
